services:
  mongo-db:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
